trigger:
  - main  # Runs the pipeline when changes are pushed to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use a Linux-based environment for the pipeline

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'  # Install Node.js (required for Juice Shop)

  - script: npm install
    displayName: 'Install dependencies'  # Download necessary software

  - script: npm run build
    displayName: 'Build the application'  # Build Juice Shop

  - script: npm test
    displayName: 'Run basic tests'  # Ensure the app works